var text = 'SATINE LIEN SILL HIPSHOT SALIENT OLIO OAT AT FELLNESSES HOPPO AS APOTHEOSES PITAPATATION TENIO FLENTES SETA VOLATA AVAST APHELIA SENIT NOEL TIT PLASS ASH SEETHE A ELL PAVONAZZETTO ASS SALESPEOPLE SOTS TOPAZINE VITIAL ELL THIASOTE INSTELLATINN AS PANTHEONIZATION NIT PHOSE THONE NOT NIPS THISTLISH PALEOLITHIST PHOTAESTHESIS PENTAIL PLOPS POPIAN PEPS PENTHIOPHENE HILT TALAS TENSIONLESS HELENN NIPPINESS SHE SELL ETHOS A SESSIONAL PASSIONIST FOAL IF TANINESS TOOLS IN LET HE SO PLANES AS FOOTFALL HISS IS TITIVATION PATTENS ZAP FIFE PATASHTE POOP LOVELIES SLIPSHEET PIANOS EEL ANTIPOPES PELTAST HONE VAS SNIP LENS TENS FAN HOTNESSES OH VELVETLEAF SANIT ALETHOPTEIS TAZIA APE AS ANTIATHEIST IS INFESTIVE STEEP FOSSATE SOLO A STOSH EPIST POT LAZE TOOL HI INN HIP ENANTIOPATHIA LINETEST TOPSAILITE SOON TZETZES LASTNESS LEAFS PAPELONNE PITA OF SAILS TAZIA NIP PLATTEN TO TIL FOVEA NOISELESSNESS TOFILE ALAS AS THALIAN HAT OOF AVITAL APPETITIONAL PET PIPS PHOTOSTATS SOFTIE LATE SHEAVES VIVAT A ESSENE SPATHA SAFETIES SALES TELOPHASE TV INVENTIONS SAT ZEE OPPOSITIONLESS PHOTS ASSISHNESS ALPINISTS PANTOFFLE HIP AN TELL POTSIE PEAN SEVENTIETHS INITIALIZES TAPELESS TOIL AHA VEEP SLOE OFFAL LOOS SIP POINTILLISTS HASTES OSTEOPLASTIES NATIVE OPINE TILETTE TEPEFIES HIT AT LEO AT SEPALINE SHEEPISHNESS EPINASTIES FAIL NEVI ZION PALATES POLLINIZE LIPS STOPT VILLITIS HE IS SPOIL SASANI HOT PINTS AVAILS PALLANESTHESIA SESTINES HEAVEN LOVE TOPOPOLITAN TAP NEIFS ON ANAESTHETIST POSTSPLENIAL SELVES FOLIO EAVES PHANTASIAST A ONES ANAL FETS OILSTONES PATENTNESS VOLATILITIES ASST ASSAILS SIVVENS SPITTLE ZAP IT FOP PAL AHAAINA TANS TIELESS TIP SHEAFS VAT FLESHPOT PAPILLAE HOES ANOIA FAN ETESIANS LEI HEPATOPTOSIA SPEEL SASHOON A FLEE TOAST HIPS OPTOPHONE TEAT ANAPAITE SOS AN ION SLOTS SEAS VOLTAPLAST LEVIATHANS TIT OOZE IT HALE IN LION SEVENTIETHS IN FEINT PIE IT NET SNIPEFISHES ALLENIATE OH SPAT HAZEN SPLITS PINNEL ASSISTIVE SHOOTS POINTAL LOSS FLAP NEOPLASIA VENAL HEAVENLESS NONINFINITE VELVETEEN LINT ASHES SPLENITIVE FAQ SATINE LIEN SILL HIPSHOT SALIENT OLIO OAT AT FELLNESSES HOPPO AS APOTHEOSES PITAPATATION TENIO FLENTES SETA VOLATA AVAST APHELIA SENIT NOEL TIT PLASS ASH SEETHE A ELL PAVONAZZETTO ASS SALESPEOPLE SOTS TOPAZINE VITIAL ELL THIASOTE INSTELLATINN AS PANTHEONIZATION NIT PHOSE THONE NOT NIPS THISTLISH PALEOLITHIST PHOTAESTHESIS PENTAIL PLOPS POPIAN PEPS PENTHIOPHENE HILT TALAS TENSIONLESS HELENN NIPPINESS SHE SELL ETHOS A SESSIONAL PASSIONIST FOAL IF TANINESS TOOLS IN LET HE SO PLANES AS FOOTFALL HISS IS TITIVATION PATTENS ZAP FIFE PATASHTE POOP LOVELIES SLIPSHEET PIANOS EEL ANTIPOPES PELTAST HONE VAS SNIP LENS TENS FAN HOTNESSES OH VELVETLEAF SANIT ALETHOPTEIS TAZIA APE AS ANTIATHEIST IS INFESTIVE STEEP FOSSATE SOLO A STOSH EPIST POT LAZE TOOL HI INN HIP ENANTIOPATHIA LINETEST TOPSAILITE SOON TZETZES LASTNESS LEAFS PAPELONNE PITA OF SAILS TAZIA NIP PLATTEN TO TIL FOVEA NOISELESSNESS TOFILE ALAS AS THALIAN HAT OOF AVITAL APPETITIONAL PET PIPS PHOTOSTATS SOFTIE LATE SHEAVES VIVAT A ESSENE SPATHA SAFETIES SALES TELOPHASE TV INVENTIONS SAT ZEE OPPOSITIONLESS PHOTS ASSISHNESS ALPINISTS PANTOFFLE HIP AN TELL POTSIE PEAN SEVENTIETHS INITIALIZES TAPELESS TOIL AHA VEEP SLOE OFFAL LOOS SIP POINTILLISTS HASTES OSTEOPLASTIES NATIVE OPINE TILETTE TEPEFIES HIT AT LEO AT SEPALINE SHEEPISHNESS EPINASTIES FAIL NEVI ZION PALATES POLLINIZE LIPS STOPT VILLITIS HE IS SPOIL SASANI HOT PINTS AVAILS PALLANESTHESIA SESTINES HEAVEN LOVE TOPOPOLITAN TAP NEIFS ON ANAESTHETIST POSTSPLENIAL SELVES FOLIO EAVES PHANTASIAST A ONES ANAL FETS OILSTONES PATENTNESS VOLATILITIES ASST ASSAILS SIVVENS SPITTLE ZAP IT FOP PAL AHAAINA TANS TIELESS TIP SHEAFS VAT FLESHPOT PAPILLAE HOES ANOIA FAN ETESIANS LEI HEPATOPTOSIA SPEEL SASHOON A FLEE TOAST HIPS OPTOPHONE TEAT ANAPAITE SOS AN ION SLOTS SEAS VOLTAPLAST LEVIATHANS TIT OOZE IT HALE IN LION SEVENTIETHS IN FEINT PIE IT NET SNIPEFISHES ALLENIATE OH SPAT HAZEN SPLITS PINNEL ASSISTIVE SHOOTS POINTAL LOSS FLAP NEOPLASIA VENAL HEAVENLESS NONINFINITE VELVETEEN LINT ASHES SPLENITIVE FAQ SATINE LIEN SILL HIPSHOT SALIENT OLIO OAT AT FELLNESSES HOPPO AS APOTHEOSES PITAPATATION TENIO FLENTES SETA VOLATA AVAST APHELIA SENIT NOEL TIT PLASS ASH SEETHE A ELL PAVONAZZETTO ASS SALESPEOPLE SOTS TOPAZINE VITIAL ELL THIASOTE INSTELLATINN AS PANTHEONIZATION NIT PHOSE THONE NOT NIPS THISTLISH PALEOLITHIST PHOTAESTHESIS PENTAIL PLOPS POPIAN PEPS PENTHIOPHENE HILT TALAS TENSIONLESS HELENN NIPPINESS SHE SELL ETHOS A SESSIONAL PASSIONIST FOAL IF TANINESS TOOLS IN LET HE SO PLANES AS FOOTFALL HISS IS TITIVATION PATTENS ZAP FIFE PATASHTE POOP LOVELIES SLIPSHEET PIANOS EEL ANTIPOPES PELTAST HONE VAS SNIP LENS TENS FAN HOTNESSES OH VELVETLEAF SANIT ALETHOPTEIS TAZIA APE AS ANTIATHEIST IS INFESTIVE STEEP FOSSATE SOLO A STOSH EPIST POT LAZE TOOL HI INN HIP ENANTIOPATHIA LINETEST TOPSAILITE SOON TZETZES LASTNESS LEAFS PAPELONNE PITA OF SAILS TAZIA NIP PLATTEN TO TIL FOVEA NOISELESSNESS TOFILE ALAS AS THALIAN HAT OOF AVITAL APPETITIONAL PET PIPS PHOTOSTATS SOFTIE LATE SHEAVES VIVAT A ESSENE SPATHA SAFETIES SALES TELOPHASE TV INVENTIONS SAT ZEE OPPOSITIONLESS PHOTS ASSISHNESS ALPINISTS PANTOFFLE HIP AN TELL POTSIE PEAN SEVENTIETHS INITIALIZES TAPELESS TOIL AHA VEEP SLOE OFFAL LOOS SIP POINTILLISTS HASTES OSTEOPLASTIES NATIVE OPINE TILETTE TEPEFIES HIT AT LEO AT SEPALINE SHEEPISHNESS EPINASTIES FAIL NEVI ZION PALATES POLLINIZE LIPS STOPT VILLITIS HE IS SPOIL SASANI HOT PINTS AVAILS PALLANESTHESIA SESTINES HEAVEN LOVE TOPOPOLITAN TAP NEIFS ON ANAESTHETIST POSTSPLENIAL SELVES FOLIO EAVES PHANTASIAST A ONES ANAL FETS OILSTONES PATENTNESS VOLATILITIES ASST ASSAILS SIVVENS SPITTLE ZAP IT FOP PAL AHAAINA TANS TIELESS TIP SHEAFS VAT FLESHPOT PAPILLAE HOES ANOIA FAN ETESIANS LEI HEPATOPTOSIA SPEEL SASHOON A FLEE TOAST HIPS OPTOPHONE TEAT ANAPAITE SOS AN ION SLOTS SEAS VOLTAPLAST LEVIATHANS TIT OOZE IT HALE IN LION SEVENTIETHS IN FEINT PIE IT NET SNIPEFISHES ALLENIATE OH SPAT HAZEN SPLITS PINNEL ASSISTIVE SHOOTS POINTAL LOSS FLAP NEOPLASIA VENAL HEAVENLESS NONINFINITE VELVETEEN LINT ASHES SPLENITIVE FAQ SATINE LIEN SILL HIPSHOT SALIENT OLIO OAT AT FELLNESSES HOPPO AS APOTHEOSES PITAPATATION TENIO FLENTES SETA VOLATA AVAST APHELIA SENIT NOEL TIT PLASS ASH SEETHE A ELL PAVONAZZETTO ASS SALESPEOPLE SOTS TOPAZINE VITIAL ELL THIASOTE INSTELLATINN AS PANTHEONIZATION NIT PHOSE THONE NOT NIPS THISTLISH PALEOLITHIST PHOTAESTHESIS PENTAIL PLOPS POPIAN PEPS PENTHIOPHENE HILT TALAS TENSIONLESS HELENN NIPPINESS SHE SELL ETHOS A SESSIONAL PASSIONIST FOAL IF TANINESS TOOLS IN LET HE SO PLANES AS FOOTFALL HISS IS TITIVATION PATTENS ZAP FIFE PATASHTE POOP LOVELIES SLIPSHEET PIANOS EEL ANTIPOPES PELTAST HONE VAS SNIP LENS TENS FAN HOTNESSES OH VELVETLEAF SANIT ALETHOPTEIS TAZIA APE AS ANTIATHEIST IS INFESTIVE STEEP FOSSATE SOLO A STOSH EPIST POT LAZE TOOL HI INN HIP ENANTIOPATHIA LINETEST TOPSAILITE SOON TZETZES LASTNESS LEAFS PAPELONNE PITA OF SAILS TAZIA NIP PLATTEN TO TIL FOVEA NOISELESSNESS TOFILE ALAS AS THALIAN HAT OOF AVITAL APPETITIONAL PET PIPS PHOTOSTATS SOFTIE LATE SHEAVES VIVAT A ESSENE SPATHA SAFETIES SALES TELOPHASE TV INVENTIONS SAT ZEE OPPOSITIONLESS PHOTS ASSISHNESS ALPINISTS PANTOFFLE HIP AN TELL POTSIE PEAN SEVENTIETHS INITIALIZES TAPELESS TOIL AHA VEEP SLOE OFFAL LOOS SIP POINTILLISTS HASTES OSTEOPLASTIES NATIVE OPINE TILETTE TEPEFIES HIT AT LEO AT SEPALINE SHEEPISHNESS EPINASTIES FAIL NEVI ZION PALATES POLLINIZE LIPS STOPT VILLITIS HE IS SPOIL SASANI HOT PINTS AVAILS PALLANESTHESIA SESTINES HEAVEN LOVE TOPOPOLITAN TAP NEIFS ON ANAESTHETIST POSTSPLENIAL SELVES FOLIO EAVES PHANTASIAST A ONES ANAL FETS OILSTONES PATENTNESS VOLATILITIES ASST ASSAILS SIVVENS SPITTLE ZAP IT FOP PAL AHAAINA TANS TIELESS TIP SHEAFS VAT FLESHPOT PAPILLAE HOES ANOIA FAN ETESIANS LEI HEPATOPTOSIA SPEEL SASHOON A FLEE TOAST HIPS OPTOPHONE TEAT ANAPAITE SOS AN ION SLOTS SEAS VOLTAPLAST LEVIATHANS TIT OOZE IT HALE IN LION SEVENTIETHS IN FEINT PIE IT NET SNIPEFISHES ALLENIATE OH SPAT HAZEN SPLITS PINNEL ASSISTIVE SHOOTS POINTAL LOSS FLAP NEOPLASIA VENAL HEAVENLESS NONINFINITE VELVETEEN LINT ASHES SPLENITIVE FAQ SATINE LIEN SILL HIPSHOT SALIENT OLIO OAT AT FELLNESSES HOPPO AS APOTHEOSES PITAPATATION TENIO FLENTES SETA VOLATA AVAST APHELIA SENIT NOEL TIT PLASS ASH SEETHE A ELL PAVONAZZETTO ASS SALESPEOPLE SOTS TOPAZINE VITIAL ELL THIASOTE INSTELLATINN AS PANTHEONIZATION NIT PHOSE THONE NOT NIPS THISTLISH PALEOLITHIST PHOTAESTHESIS PENTAIL PLOPS POPIAN PEPS PENTHIOPHENE HILT TALAS TENSIONLESS HELENN NIPPINESS SHE SELL ETHOS A SESSIONAL PASSIONIST FOAL IF TANINESS TOOLS IN LET HE SO PLANES AS FOOTFALL HISS IS TITIVATION PATTENS ZAP FIFE PATASHTE POOP LOVELIES SLIPSHEET PIANOS EEL ANTIPOPES PELTAST HONE VAS SNIP LENS TENS FAN HOTNESSES OH VELVETLEAF SANIT ALETHOPTEIS TAZIA APE AS ANTIATHEIST IS INFESTIVE STEEP FOSSATE SOLO A STOSH EPIST POT LAZE TOOL HI INN HIP ENANTIOPATHIA LINETEST TOPSAILITE SOON TZETZES LASTNESS LEAFS PAPELONNE PITA OF SAILS TAZIA NIP PLATTEN TO TIL FOVEA NOISELESSNESS TOFILE ALAS AS THALIAN HAT OOF AVITAL APPETITIONAL PET PIPS PHOTOSTATS SOFTIE LATE SHEAVES VIVAT A ESSENE SPATHA SAFETIES SALES TELOPHASE TV INVENTIONS SAT ZEE OPPOSITIONLESS PHOTS ASSISHNESS ALPINISTS PANTOFFLE HIP AN TELL POTSIE PEAN SEVENTIETHS INITIALIZES TAPELESS TOIL AHA VEEP SLOE OFFAL LOOS SIP POINTILLISTS HASTES OSTEOPLASTIES NATIVE OPINE TILETTE TEPEFIES HIT AT LEO AT SEPALINE SHEEPISHNESS EPINASTIES FAIL NEVI ZION PALATES POLLINIZE LIPS STOPT VILLITIS HE IS SPOIL SASANI HOT PINTS AVAILS PALLANESTHESIA SESTINES HEAVEN LOVE TOPOPOLITAN TAP NEIFS ON ANAESTHETIST POSTSPLENIAL SELVES FOLIO EAVES PHANTASIAST A ONES ANAL FETS OILSTONES PATENTNESS VOLATILITIES ASST ASSAILS SIVVENS SPITTLE ZAP IT FOP PAL AHAAINA TANS TIELESS TIP SHEAFS VAT FLESHPOT PAPILLAE HOES ANOIA FAN ETESIANS LEI HEPATOPTOSIA SPEEL SASHOON A FLEE TOAST HIPS OPTOPHONE TEAT ANAPAITE SOS AN ION SLOTS SEAS VOLTAPLAST LEVIATHANS TIT OOZE IT HALE IN LION SEVENTIETHS IN FEINT PIE IT NET SNIPEFISHES ALLENIATE OH SPAT HAZEN SPLITS PINNEL ASSISTIVE SHOOTS POINTAL LOSS FLAP NEOPLASIA VENAL HEAVENLESS NONINFINITE VELVETEEN LINT ASHES SPLENITIVE FAQ SATINE LIEN SILL HIPSHOT SALIENT OLIO OAT AT FELLNESSES HOPPO AS APOTHEOSES PITAPATATION TENIO FLENTES SETA VOLATA AVAST APHELIA SENIT NOEL TIT PLASS ASH SEETHE A ELL PAVONAZZETTO ASS SALESPEOPLE SOTS TOPAZINE VITIAL ELL THIASOTE INSTELLATINN AS PANTHEONIZATION NIT PHOSE THONE NOT NIPS THISTLISH PALEOLITHIST PHOTAESTHESIS PENTAIL PLOPS POPIAN PEPS PENTHIOPHENE HILT TALAS TENSIONLESS HELENN NIPPINESS SHE SELL ETHOS A SESSIONAL PASSIONIST FOAL IF TANINESS TOOLS IN LET HE SO PLANES AS FOOTFALL HISS IS TITIVATION PATTENS ZAP FIFE PATASHTE POOP LOVELIES SLIPSHEET PIANOS EEL ANTIPOPES PELTAST HONE VAS SNIP LENS TENS FAN HOTNESSES OH VELVETLEAF SANIT ALETHOPTEIS TAZIA APE AS ANTIATHEIST IS INFESTIVE STEEP FOSSATE SOLO A STOSH EPIST POT LAZE TOOL HI INN HIP ENANTIOPATHIA LINETEST TOPSAILITE SOON TZETZES LASTNESS LEAFS PAPELONNE PITA OF SAILS TAZIA NIP PLATTEN TO TIL FOVEA NOISELESSNESS TOFILE ALAS AS THALIAN HAT OOF AVITAL APPETITIONAL PET PIPS PHOTOSTATS SOFTIE LATE SHEAVES VIVAT A ESSENE SPATHA SAFETIES SALES TELOPHASE TV INVENTIONS SAT ZEE OPPOSITIONLESS PHOTS ASSISHNESS ALPINISTS PANTOFFLE HIP AN TELL POTSIE PEAN SEVENTIETHS INITIALIZES TAPELESS TOIL AHA VEEP SLOE OFFAL LOOS SIP POINTILLISTS HASTES OSTEOPLASTIES NATIVE OPINE TILETTE TEPEFIES HIT AT LEO AT SEPALINE SHEEPISHNESS EPINASTIES FAIL NEVI ZION PALATES POLLINIZE LIPS STOPT VILLITIS HE IS SPOIL SASANI HOT PINTS AVAILS PALLANESTHESIA SESTINES HEAVEN LOVE TOPOPOLITAN TAP NEIFS ON ANAESTHETIST POSTSPLENIAL SELVES FOLIO EAVES PHANTASIAST A ONES ANAL FETS OILSTONES PATENTNESS VOLATILITIES ASST ASSAILS SIVVENS SPITTLE ZAP IT FOP PAL AHAAINA TANS TIELESS TIP SHEAFS VAT FLESHPOT PAPILLAE HOES ANOIA FAN ETESIANS LEI HEPATOPTOSIA SPEEL SASHOON A FLEE TOAST HIPS OPTOPHONE TEAT ANAPAITE SOS AN ION SLOTS SEAS VOLTAPLAST LEVIATHANS TIT OOZE IT HALE IN LION SEVENTIETHS IN FEINT PIE IT NET SNIPEFISHES ALLENIATE OH SPAT HAZEN SPLITS PINNEL ASSISTIVE SHOOTS POINTAL LOSS FLAP NEOPLASIA VENAL HEAVENLESS NONINFINITE VELVETEEN LINT ASHES SPLENITIVE FAQ'
var left_array = []

        document.addEventListener('touchmove', function(e) {
        e.preventDefault();
        }, { passive: false });

    $(document).ready(function(){
var isMobile = false; //initiate as false
// device detection
if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|ipad|iris|kindle|Android|Silk|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(navigator.userAgent) 
    || /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,4))) { 
    isMobile = true;
    console.log('het')
    $('body').addClass('mobile')
}else{
    $('body').addClass('desktop')
}



        counter_init++
        ready = true
        var option_x = []
        var option_y = []

        $('body').append('<div class="wrapper wrapper_'+counter_init+' wrapper_text"></div>')
        for (var i = 100; i < text.split('').length; i++) {
        	$('.wrapper_'+counter_init).append("<span class='element element_"+i+"'>"+text.split('')[i]+"</span>")

            if(i == text.split('').length-1){

                setTimeout(function(){
                    $('.element').each(function(){
                        var x = Math.floor(($(this).offset().left-2)/4)*4+4
                        var y = Math.floor(($(this).offset().top-2)/4)*4+4

                        if(!option_x.includes(x) && x >=0){
                            option_x.push(x)
                        }
                        if(!option_y.includes(y) && y >=0){
                            option_y.push(y)
                        }
                        // console.log(option_x)
                        // console.log(option_y)

                            $(this).addClass('pos_'+x+'_'+y)
                    })
                },1000)
            }




        }
        $('.element').each(function(){
            $(this).hover(function(){
              $(this).addClass('fadeout')  
            },function(){
              $(this).removeClass('fadeout')  
            })

        })

        var timeout;

        $(document).on('touchstart', function(e) {
            console.log('0')
            $(this).addClass('hovered')
            clearTimeout(timeout);
            // event.touches[0].pageY

        })
        $(document).on('touchmove', function(e) {
            clearTimeout(timeout);
            timeout = setTimeout(function(){
                $('.fadeout').removeClass('fadeout')
                console.log('1')
            }, 500);


            $('.fadeout').removeClass('fadeout')
            for (var i = option_y.length - 1; i >= 0; i--) {
                for (var j = option_x.length - 1; j >= 0; j--) {
                    if(event.touches[0].pageY>option_y[i] && event.touches[0].pageY<option_y[i+1]&&
                        event.touches[0].pageX>option_x[j] && event.touches[0].pageX<option_x[j+1]
                        ){
                        $('.pos_'+option_x[j]+'_'+option_y[i]).addClass('fadeout')
                    }
                }
            }
            $(this).addClass('hovered')
        })

        $(document).on('touchend', function(e) {
            console.log('he')
            $('.fadeout').removeClass('fadeout')

        })









    })